# Generated by Django 2.1.5 on 2021-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image',
        ),
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ManyToManyField(to='animals.AnimalPicture'),
        ),
    ]
