# Generated by Django 2.1.5 on 2021-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalpicture',
            name='image',
            field=models.ImageField(upload_to='animals/pictures'),
        ),
    ]
