# Generated by Django 2.1.5 on 2021-03-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
