# Generated by Django 2.1.5 on 2021-03-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20210312_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='tags',
            field=models.ManyToManyField(to='animals.Tag'),
        ),
    ]
