# Generated by Django 2.1.5 on 2021-03-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20210312_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalpicture',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
