# Generated by Django 2.1.5 on 2021-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_auto_20210320_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalpicture',
            name='url',
            field=models.CharField(default='media/<django.db.models.fields.CharField>', max_length=240),
        ),
    ]
