# Generated by Django 2.1.5 on 2021-03-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20210320_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalpicture',
            name='urls',
        ),
    ]
