# Generated by Django 2.1.5 on 2021-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0011_animal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='writer',
            field=models.CharField(default='Lucas Lassiter', max_length=120),
            preserve_default=False,
        ),
    ]
